"""Generates common/scripted_triggers/nr_amendment_room.txt (pattern "Room in the law", README_NR.md):
the list of our amendments (every amendment_nr_* in common/amendments) and the opposing sponsors per law group.

Run after adding an amendment or an opposing pair:  python tools/gen_amendment_room.py
check_mod.py calls generate() and reports the file if it is out of date."""
import glob
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, 'common', 'scripted_triggers', 'nr_amendment_room.txt')
IGS = ['ig_armed_forces', 'ig_devout', 'ig_industrialists', 'ig_intelligentsia', 'ig_landowners', 'ig_petty_bourgeoisie',
       'ig_rural_folk', 'ig_trade_unions']

# Opposing sponsors per law group: (comment, laws of the group, group a, group b). Agreed with the user.
OPPOSITION = [
    ('slavery', ['law_slavery_banned', 'law_slave_trade', 'law_legacy_slavery', 'law_colonial_slavery', 'law_debt_slavery'],
     'ig_devout', 'ig_landowners'),
    ('policing', ['law_no_police', 'law_local_police', 'law_dedicated_police', 'law_militarized_police'], 'ig_devout', 'ig_landowners'),
    ('economic system', ['law_traditionalism', 'law_interventionism', 'law_agrarianism', 'law_industry_banned', 'law_extraction_economy',
                         'law_laissez_faire', 'law_cooperative_ownership', 'law_command_economy'], 'ig_industrialists', 'ig_landowners'),
    ('labour', ['law_no_workers_rights', 'law_regulatory_bodies', 'law_worker_protections', 'law_guild_system', 'law_combination_acts',
                'law_anti_strike_laws', 'law_right_to_associate', 'law_corporatized_unions', 'law_factory_councils'],
     'ig_industrialists', 'ig_trade_unions'),
]


def law_in(laws, scope=''):
    body = 'OR = { ' + ' '.join(f'type = law_type:{l}' for l in laws) + ' }'
    return f'{scope} = {{ {body} }}' if scope else body


def generate():
    ours = sorted({a for f in glob.glob(os.path.join(ROOT, 'common', 'amendments', '*.txt'))
                   for a in re.findall(r'(?m)^(amendment_nr_[a-z_]+) = \{', open(f, encoding='utf-8-sig').read())})
    out = ['''# NR: room in the law for our amendments (pattern "Room in the law", README_NR.md).
# GENERATED by tools/gen_amendment_room.py - do not edit by hand; edit the script and run it.
# A law carries at most 2 of our amendments, and no two of them may come from groups that oppose each other on that
# law (opposition is per law group). Vanilla and other mods' amendments do not count.

# The amendment is one of ours. Scope: amendment.
nr_amendment_is_ours = {
	OR = {
''' + ''.join(f'\t\ttype = amendment_type:{a}\n' for a in ours) + '''	}
}

# There is room on the law for a new amendment sponsored by $IG$. Scope: law.
nr_amendment_fits = {
	NOT = {
		any_scope_amendment = {
			count >= 2
			nr_amendment_is_ours = yes
		}
	}
	nr_amendment_opposed_$IG$ = no
}
''']
    for g in IGS:
        parts = []
        for name, laws, a, b in OPPOSITION:
            if g in (a, b):
                other = b if g == a else a
                parts.append(f'''		AND = {{ # {name}
			{law_in(laws)}
			any_scope_amendment = {{
				nr_amendment_is_ours = yes
				sponsor ?= {{ is_interest_group_type = {other} }}
			}}
		}}
''')
        body = ('\tOR = {\n' + ''.join(parts) + '\t}\n') if parts else '\talways = no # no opposing group on any law yet\n'
        out.append(f'\n# The law carries an amendment of a group opposing {g} on this law. Scope: law.\nnr_amendment_opposed_{g} = {{\n{body}}}\n')
    out.append('''
# In event nr_amendment_room.1: this amendment's sponsor opposes the sponsor of the new one on this law. Scope: amendment.
nr_amendment_opposes_room = {
	nr_amendment_is_ours = yes
	OR = {
''' + ''.join(f'''		AND = {{ # {name}
			{law_in(laws, 'scope:room_law')}
			OR = {{
				AND = {{
					scope:room_ig = {{ is_interest_group_type = {a} }}
					sponsor ?= {{ is_interest_group_type = {b} }}
				}}
				AND = {{
					scope:room_ig = {{ is_interest_group_type = {b} }}
					sponsor ?= {{ is_interest_group_type = {a} }}
				}}
			}}
		}}
''' for name, laws, a, b in OPPOSITION) + '''	}
}
''')
    return '﻿' + ''.join(out)


if __name__ == '__main__':
    open(TARGET, 'w', encoding='utf-8', newline='').write(generate())
    print('written', TARGET)
